export const GEO_URL = "https://cdn.jsdelivr.net/npm/world-atlas@2/countries-110m.json";

export const MAP_CONFIG = {
  projection: "geoNaturalEarth1" as const,
  scale: 140,
  center: [0, 20] as [number, number],
  width: 800,
  height: 400,
} as const;

export const COLOR_SCALE = {
  noData: '#f3f4f6',
  veryLow: '#f0f9ff',
  low: '#dbeafe',
  lowMedium: '#bfdbfe',
  mediumLight: '#93c5fd',
  medium: '#60a5fa',
  blue: '#3b82f6',
  mediumDark: '#2563eb',
  dark: '#1d4ed8',
  veryDark: '#1e40af',
  darkest: '#1e3a8a',
} as const;

export const COLOR_THRESHOLDS = {
  veryLow: 0.1,
  low: 0.2,
  lowMedium: 0.3,
  mediumLight: 0.4,
  medium: 0.5,
  blue: 0.6,
  mediumDark: 0.7,
  dark: 0.8,
  veryDark: 0.9,
} as const;

export const COUNTRY_NAME_MAP: Record<string, string> = {
  'US': 'United States of America',
  'CN': 'China',
  'DE': 'Germany',
  'GB': 'United Kingdom',
  'IT': 'Italy',
  'FR': 'France',
  'JP': 'Japan',
  'CA': 'Canada',
  'AU': 'Australia',
  'ES': 'Spain',
  'RU': 'Russia',
  'IN': 'India',
  'BR': 'Brazil',
  'MX': 'Mexico',
  'KR': 'South Korea',
  'IR': 'Iran',
  'SG': 'Singapore',
  'HK': 'Hong Kong',
  
  'AT': 'Austria',
  'CH': 'Switzerland',
  'NL': 'Netherlands',
  'PL': 'Poland',
  'IL': 'Israel',
  'BE': 'Belgium',
  'SE': 'Sweden',
  'DK': 'Denmark',
  'FI': 'Finland',
  'CZ': 'Czech Republic',
  'HU': 'Hungary',
  'NO': 'Norway',
  
  'TH': 'Thailand',
  'VN': 'Vietnam',
  'ID': 'Indonesia',
  'MY': 'Malaysia',
  'PH': 'Philippines',
  'EG': 'Egypt',
  'ZA': 'South Africa',
  'NG': 'Nigeria',
  'KE': 'Kenya',
  'AR': 'Argentina',
  'CL': 'Chile',
  'NZ': 'New Zealand',
  'PK': 'Pakistan',
  'BD': 'Bangladesh',
  'SA': 'Saudi Arabia',
  'AE': 'United Arab Emirates',
  'TR': 'Turkey',
  'GR': 'Greece',
  'RO': 'Romania',
  'BG': 'Bulgaria',
  'PT': 'Portugal',
  'IE': 'Ireland',
  'IS': 'Iceland',
  'LT': 'Lithuania',
  'LV': 'Latvia',
  'EE': 'Estonia',
  'CY': 'Cyprus',
  'MT': 'Malta',
  'SI': 'Slovenia',
  'HR': 'Croatia',
  'BA': 'Bosnia and Herzegovina',
  'ME': 'Montenegro',
  'AL': 'Albania',
  'MK': 'Macedonia',
  'RS': 'Serbia',
  'UA': 'Ukraine',
  'MD': 'Moldova',
  'AM': 'Armenia',
  'GE': 'Georgia',
  'AZ': 'Azerbaijan',
  'TM': 'Turkmenistan',
  'KZ': 'Kazakhstan',
  'UZ': 'Uzbekistan',
  'KG': 'Kyrgyzstan',
  'TJ': 'Tajikistan',
  'SY': 'Syria',
  'YE': 'Yemen',
  'OM': 'Oman',
  'QA': 'Qatar',
  'BH': 'Bahrain',
  'KW': 'Kuwait'
} as const;

export const TOOLTIP_CONFIG = {
  maxWidth: 'max-w-sm',
  pinnedPosition: { left: '20px', top: '20px' },
  offset: { x: 10, y: -10 },
  maxPosition: { x: 300, y: 200 },
} as const;

export const LEGEND_ITEMS = [
  { color: COLOR_SCALE.noData, label: 'No data' },
  { color: COLOR_SCALE.veryLow, label: 'Very Low' },
  { color: COLOR_SCALE.low, label: 'Low' },
  { color: COLOR_SCALE.medium, label: 'Medium' },
  { color: COLOR_SCALE.dark, label: 'High' },
  { color: COLOR_SCALE.darkest, label: 'Very High' },
] as const;

export const INTENSITY_LABELS = {
  veryHigh: 'Very High',
  high: 'High',
  medium: 'Medium',
  low: 'Low',
  veryLow: 'Very Low',
} as const;

export const INTENSITY_THRESHOLDS = {
  veryHigh: 80,
  high: 60,
  medium: 40,
  low: 20,
} as const;
